services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SeoBundle\EventListener\Admin\AssetListener:
        tags:
            - { name: kernel.event_subscriber }

    SeoBundle\EventListener\PimcoreElementListener:
        arguments:
            $enabled: '%seo.index.pimcore_element_watcher.enabled%'
        tags:
            - { name: kernel.event_subscriber }

    SeoBundle\EventListener\AutoMetaDataAttachListener:
        arguments:
            $configuration: '%seo.meta_data_provider.configuration%'
        tags:
            - { name: kernel.event_subscriber }

    SeoBundle\EventListener\ElementMetaDataListener:
        tags:
            - { name: kernel.event_subscriber }
