services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SeoBundle\Repository\QueueEntryRepositoryInterface: '@SeoBundle\Repository\QueueEntryRepository'
    SeoBundle\Repository\QueueEntryRepository: ~

    SeoBundle\Repository\ElementMetaDataRepositoryInterface: '@SeoBundle\Repository\ElementMetaDataRepository'
    SeoBundle\Repository\ElementMetaDataRepository: ~

