services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SeoBundle\Registry\ResourceProcessorRegistryInterface: '@SeoBundle\Registry\ResourceProcessorRegistry'
    SeoBundle\Registry\ResourceProcessorRegistry: ~
