# Admin Routes
seo.controller.admin.meta_data.get_meta_definitions:
    path: /admin/seo/meta-data/get-meta-definitions
    defaults: { _controller: SeoBundle\Controller\Admin\MetaDataController::getMetaDataDefinitionsAction }
seo.controller.admin.meta_data.get_element_meta_data_configuration:
    path: /admin/seo/meta-data/get-element-meta-data-configuration
    defaults: { _controller: SeoBundle\Controller\Admin\MetaDataController::getElementMetaDataConfigurationAction }
seo.controller.admin.meta_data.set_element_meta_data_configuration:
    methods: [POST]
    path: /admin/seo/meta-data/set-element-meta-data-configuration
    defaults: { _controller: SeoBundle\Controller\Admin\MetaDataController::setElementMetaDataConfigurationAction }
