services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SeoBundle\Command\QueuedIndexDataCommand:
        tags:
            - { name: console.command, command: 'seo:check-index-queue' }