services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    SeoBundle\Controller\Admin\MetaDataController:
        calls:
            - [setContainer, ['@service_container']]
