services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SeoBundle\EventListener\PimcoreElementListener:
        arguments:
            $enabled: '%seo.index.pimcore_element_watcher.enabled%'
        tags:
            - { name: kernel.event_subscriber }
