services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SeoBundle\Registry\MetaDataIntegratorRegistryInterface: '@SeoBundle\Registry\MetaDataIntegratorRegistry'
    SeoBundle\Registry\MetaDataIntegratorRegistry: ~

    SeoBundle\Manager\ElementMetaDataManagerInterface: '@SeoBundle\Manager\ElementMetaDataManager'
    SeoBundle\Manager\ElementMetaDataManager:
        arguments:
            $integratorConfiguration: '%seo.meta_data_integrator.configuration%'

    SeoBundle\MetaData\Integrator\TitleDescriptionIntegrator:
        tags:
            - {name: seo.meta_data.integrator, identifier: title_description }

    SeoBundle\MetaData\Integrator\OpenGraphIntegrator:
        tags:
            - {name: seo.meta_data.integrator, identifier: open_graph }

    SeoBundle\MetaData\Integrator\SchemaIntegrator:
        tags:
            - {name: seo.meta_data.integrator, identifier: schema }

    SeoBundle\MetaData\Integrator\HtmlTagIntegrator:
        tags:
            - {name: seo.meta_data.integrator, identifier: html_tag }