services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SeoBundle\Queue\QueueDataProcessorInterface: '@SeoBundle\Queue\QueueDataProcessor'
    SeoBundle\Queue\QueueDataProcessor: ~
