services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SeoBundle\Tool\UrlGeneratorInterface: '@SeoBundle\Tool\UrlGenerator'
    SeoBundle\Tool\UrlGenerator: ~